// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjoRryrbLa3pqfpx5V7r9JQN0B_II22Fc',
    appId: '1:512917049152:web:3c476f06cfa89dd806b4a5',
    messagingSenderId: '512917049152',
    projectId: 'figuritasapp-47f0a',
    authDomain: 'figuritasapp-47f0a.firebaseapp.com',
    storageBucket: 'figuritasapp-47f0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABRNXF_4biEasOubWSU_Jy7kINesxbLP8',
    appId: '1:512917049152:android:226fbe3b4868d63e06b4a5',
    messagingSenderId: '512917049152',
    projectId: 'figuritasapp-47f0a',
    storageBucket: 'figuritasapp-47f0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuAg0sXeoBILFUngHyAJQxolRqUxtTwas',
    appId: '1:512917049152:ios:d648bfecaad79f9206b4a5',
    messagingSenderId: '512917049152',
    projectId: 'figuritasapp-47f0a',
    storageBucket: 'figuritasapp-47f0a.firebasestorage.app',
    iosBundleId: 'com.example.albumMundialVc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuAg0sXeoBILFUngHyAJQxolRqUxtTwas',
    appId: '1:512917049152:ios:d648bfecaad79f9206b4a5',
    messagingSenderId: '512917049152',
    projectId: 'figuritasapp-47f0a',
    storageBucket: 'figuritasapp-47f0a.firebasestorage.app',
    iosBundleId: 'com.example.albumMundialVc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjoRryrbLa3pqfpx5V7r9JQN0B_II22Fc',
    appId: '1:512917049152:web:b0c398a13e81287f06b4a5',
    messagingSenderId: '512917049152',
    projectId: 'figuritasapp-47f0a',
    authDomain: 'figuritasapp-47f0a.firebaseapp.com',
    storageBucket: 'figuritasapp-47f0a.firebasestorage.app',
  );
}
